<?php
$data = $block->getAllData();
$first_name = '';
$last_name = '';
$email_id = '';
$phone_number = '';
$message = '';

if ($data->getid()) {
    $first_name = $data->getfirst_name();
    $last_name = $data->getlast_name();
    $email_id = $data->getemail_id();
    $phone_number = $data->getphone_number();
    $message = $data->getmessage();
}
?>
<div class="pdfinvoice">    
    <div class="pdfinvoice-form">
        <form 
            id="pdfinvoice-form" 
            name="pdfinvoice" 
            action="<?= $block->getFormAction() ?>" 
            method="POST" 
            enctype="multipart/form-data" 
            autocomplete="on" 
            data-mage-init='{"validation": {}}'
        >
            <?php if ($data->getid()): ?>
                <input type="text" name="id" value="<?= $data->getid() ?>">
            <?php endif; ?>
            <fieldset class="fieldset">
                <div class="field required">
                    <label for="first_name" id="first_name" class="label"> <?= __('First Name') ?></label>                                
                    <div class="control">
                        <input type="text" name="first_name" class="control required-entry" id="first_name" value="<?= $first_name ?>">
                    </div>
                </div>
                <div class="field required">
                    <label for="last_name" id="last_name" class="label"> <?= __('Last Name') ?></label>                                
                    <div class="control">
                        <input type="text" name="last_name" class="control required-entry" id="last_name" value="<?= $last_name ?>">
                    </div>
                </div>
                <div class="field required">
                    <label for="email_id" id="email_id" class="label"><?= __('Email address') ?></label>
                    <div class="control">
                        <input type="email" name="email_id" class="required-entry" id="email_id" value="<?= $email_id ?>">
                    </div>
                </div>
                <div class="field required">
                    <label for="phone_number" id="phone_number" class="label"> <?= __('Phone Number') ?></label>                                <div class="control">
                        <input type="text" name="phone_number" class="control required-entry" id="phone_number" value="<?= $phone_number ?>">
                    </div>
                </div>
                <div class="field required">
                    <label for="message" id="message" class="label"> <?= __('Message') ?></label>                                
                    <div class="control">
                        <input type="text" name="message" class="control required-entry" id="message" value="<?= $message ?>">
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" id="saveButton" class="action submit primary" title="<?= __('Save') ?>"><span><?= __('Save') ?></span></button>
                </div>
            </div>
        </form>        
    </div>
</div>
