<?php
$pdfinvoice = $block->getAllpdfinvoice();

if (!empty($pdfinvoice)):
?>
    <table border="1">
        <tr>
            <th><?= __("ID") ?></th>
            <th><?= __("First Name") ?></th>
            <th><?= __("Last Name") ?></th>
            <th><?= __("Email") ?></th>
            <th><?= __("Phone Number") ?></th>
            <th><?= __("Action") ?></th>
        </tr>

        <?php foreach ($pdfinvoice as $pdf): ?>
            <tr>
                <td><?= $pdf->getid() ?></td>
                <td><?= $pdf->getfirst_name() ?></td>
                <td><?= $pdf->getlast_name() ?></td>
                <td><?= $pdf->getemail_id() ?></td>
                <td><?= $pdf->getphone_number() ?></td>
                <td>
                <a style="color: red;" href="#" onclick="showConfirmation('<?= $block->getDeleteAction() . 'id/' . $pdf->getId() ?>')">
                        <?= __('Delete') ?>
                    </a>
                                        
                    <a style="margin-left: 9px; color: green"
                           href="<?= $block->getEditAction() . 'id/' . $pdf->getId(); ?>"><?php echo __('Edit') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>	
    </table>
<?php else: ?>
    <h1><?= __("No data is found") ?></h1>
<?php endif; ?>



<script>
    function showConfirmation(deleteUrl) {
        var confirmation = confirm("Are you sure you want to delete this item?");
        if (confirmation) {
            window.location.href = deleteUrl;
        }
    }
</script>
<style>
    .logout{
        position: absolute; 
        top: 10px; 
        right: 10px;
    }

</style>