<div class="login-details">
    <form action="<?php echo $block->getUrl('form/index/login'); ?>" method="post">
        <button type="submit" class="logout">Login</button>
    </form>
</div>
<div class="login">
    <div class="login-form">
       <form
            id="login-form"
            name="login"
            action="<?= $block->getFormAction(); ?>"
            method="POST"
            enctype="multipart/form-data"
            autocomplete="on"
            data-mage-init='{"validation": {}}'
        >
        <fieldset class="fieldset">
            <div class="field required">
                <label for="email_id" id="email_id" class="label"><?= __('Email address') ?></label>
                <div class="control">
                    <input type="email" name="email_id" class="required-entry" id="email_id">
                        <span id="email_id_error" class="error-message"></span>
                </div>
            </div>
            <div class="field required">
                <label for="password" id="password" class="label"> <?= __('Password') ?></label>
                <div class="control">
                    <input type="password" name="password" class="control required-entry" id="password">
                        <span id="password_error" class="error-message"></span>
                        <span class="show-password-icon" onclick="togglePasswordVisibility()"></span>
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" id="signButton" class="action submit primary" title="<?= __('Login') ?>"><span><?= __('Signin') ?></span></button>
                </div>
            </div>
            <br>
            <div class="secondary">
                Don't have an account?
                <small><u><a href="<?php echo $this->getUrl('form/index/details'); ?>" class="login-fpwd">Register now</a></u></small>
            </div>
        </fieldset>
       </form>  
    </div>  
</div>
<style>
    
    .error-message {
        color: #CE615C;
    }
.login-details {
        text-align: right;
        padding: 20px;   
    }

</style>